version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    container_name: backend
    env_file:
      - ./config/.env.development
    depends_on:
      - database
    ports:
      - '4000:5001'
      - '4000:5002'
      - '5001'
      - '5002'

  database:
    build:
      image: postgres
    restart: always
    container_name: database
    volumes:
      - /Users/var/lib/postgres
    env_file:
      - ./config/.env.development
    environment:
      - DATABASE_HOST: ${DB_HOST}
      - DATABASE_PORT: ${DB_PORT}
      - DATABASE_USERNAME: ${DB_USERNAME}
      - DATABASE_PASSWORD: ${DB_PASSWORD}
      - DATABASE_NAME: ${DB_NAME}
    ports:
      - '5432:5432'
      - '5432'
